In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import numpy as np
import sklearn.metrics

In [23]:
df = pd.read_csv("..//data_mart//reporting_cb.csv")
hold_out_year = 2017

In [24]:
test_df = df.loc[df['draft_year'] == hold_out_year]

In [25]:
bool_series = pd.notnull(df['max_madden'])
train_df = df[bool_series]
train_df = train_df.loc[train_df['draft_year'] != hold_out_year]

In [26]:
cols = train_df.columns
for value in cols:
    print(value)

fms_id
espn_id
full_name
first_name
last_name
position
position_group
section
college
draft_year
selection_number
position_rank
position_group_rank
section_rank
drafting_team
home_city
home_state
home_country
college_weight_pounds
college_height_inches
hw_ratio
forty
vertical
bench
broad
threecone
shuttle
defense_ast_tackles_pg
defense_fum_forced_pg
defense_fum_rec_pg
defense_fum_tds_pg
defense_fum_yds_pg
defense_int_pg
defense_int_td_pg
defense_int_yards_pg
defense_loss_tackles_pg
defense_pd_pg
defense_sacks_pg
defense_solo_tackes_pg
defense_tackles_pg
defense_ast_tackles_pg_cf_scaled
defense_fum_forced_pg_cf_scaled
defense_fum_rec_pg_cf_scaled
defense_fum_tds_pg_cf_scaled
defense_fum_yds_pg_cf_scaled
defense_int_pg_cf_scaled
defense_int_td_pg_cf_scaled
defense_int_yards_pg_cf_scaled
defense_loss_tackles_pg_cf_scaled
defense_pd_pg_cf_scaled
defense_sacks_pg_cf_scaled
defense_solo_tackes_pg_cf_scaled
defense_tackles_pg_cf_scaled
football_spending
coaches_salaries
ticket_sales
ann_rain_inch
ann_snow_inch
min_jan
min_feb
min_mar
min_apr
min_may
min_jun
min_jul
min_aug
min_sep
min_oct
min_nov
min_dec
max_jan
max_feb
max_mar
max_apr
max_may
max_jun
max_jul
max_aug
max_sep
max_oct
max_nov
max_dec
cb_college_weight_pounds_zscore
cb_college_height_inches_zscore
cb_hw_ratio_zscore
cb_forty_zscore
cb_vertical_zscore
cb_bench_zscore
cb_broad_zscore
cb_threecone_zscore
cb_shuttle_zscore
cb_defense_ast_tackles_pg_zscore
cb_defense_fum_forced_pg_zscore
cb_defense_fum_rec_pg_zscore
cb_defense_fum_tds_pg_zscore
cb_defense_fum_yds_pg_zscore
cb_defense_int_pg_zscore
cb_defense_int_td_pg_zscore
cb_defense_int_yards_pg_zscore
cb_defense_loss_tackles_pg_zscore
cb_defense_pd_pg_zscore
cb_defense_sacks_pg_zscore
cb_defense_solo_tackes_pg_zscore
cb_defense_tackles_pg_zscore
cb_defense_ast_tackles_pg_cf_scaled_zscore
cb_defense_fum_forced_pg_cf_scaled_zscore
cb_defense_fum_rec_pg_cf_scaled_zscore
cb_defense_fum_tds_pg_cf_scaled_zscore
cb_defense_fum_yds_pg_cf_scaled_zscore
cb_defense_int_pg_cf_scaled_zscore
cb_defense_int_td_pg_cf_scaled_zscore
cb_defense_int_yards_pg_cf_scaled_zscore
cb_defense_loss_tackles_pg_cf_scaled_zscore
cb_defense_pd_pg_cf_scaled_zscore
cb_defense_sacks_pg_cf_scaled_zscore
cb_defense_solo_tackes_pg_cf_scaled_zscore
cb_defense_tackles_pg_cf_scaled_zscore
cb_football_spending_zscore
cb_coaches_salaries_zscore
cb_ticket_sales_zscore
cb_ann_rain_inch_zscore
cb_ann_snow_inch_zscore
cb_min_jan_zscore
cb_min_feb_zscore
cb_min_mar_zscore
cb_min_apr_zscore
cb_min_may_zscore
cb_min_jun_zscore
cb_min_jul_zscore
cb_min_aug_zscore
cb_min_sep_zscore
cb_min_oct_zscore
cb_min_nov_zscore
cb_min_dec_zscore
cb_max_jan_zscore
cb_max_feb_zscore
cb_max_mar_zscore
cb_max_apr_zscore
cb_max_may_zscore
cb_max_jun_zscore
cb_max_jul_zscore
cb_max_aug_zscore
cb_max_sep_zscore
cb_max_oct_zscore
cb_max_nov_zscore
cb_max_dec_zscore
cb_max_madden_zscore
max_madden

In [27]:
numerical_columns = ['cb_hw_ratio_zscore', 'cb_forty_zscore', 'cb_vertical_zscore', 'cb_bench_zscore', 'cb_broad_zscore', 'cb_threecone_zscore','cb_shuttle_zscore'
                     ,'cb_football_spending_zscore', 'cb_ann_rain_inch_zscore', 
                    'cb_defense_ast_tackles_pg_cf_scaled_zscore', 'cb_defense_fum_forced_pg_cf_scaled_zscore','cb_defense_fum_rec_pg_cf_scaled_zscore','cb_defense_int_pg_cf_scaled_zscore','cb_defense_loss_tackles_pg_cf_scaled_zscore',
'cb_defense_pd_pg_cf_scaled_zscore','cb_defense_sacks_pg_cf_scaled_zscore','cb_defense_solo_tackes_pg_cf_scaled_zscore','cb_defense_tackles_pg_cf_scaled_zscore']

In [28]:
X = train_df[numerical_columns]
y = train_df['max_madden']

In [29]:
regr = RandomForestRegressor(random_state=0)
X = X.fillna(0)
regr.fit(X,y)

c:\users\b\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [30]:
test_df = test_df.fillna(0)
preds = regr.predict(test_df[numerical_columns])

In [31]:
test_df['max_madden'] = test_df['max_madden'].replace(0, 65)
print(test_df[['full_name', 'max_madden']])

               full_name  max_madden
71        Adoree Jackson        83.0
72   Ahkello Witherspoon        75.0
73         Arthur Maulet        66.0
74        Ashton Lampkin        65.0
75           Brian Allen        69.0
76        Cameron Sutton        69.0
77    Channing Stribling        62.0
78        Chidobe Awuzie        82.0
79    Cordrea Tankersley        74.0
80            Corn Elder        70.0
81        Damontae Kazee        79.0
82         Ezra Robinson        62.0
83         Fabian Moreau        74.0
84         Gareon Conley        79.0
85         Howard Wilson        69.0
86            Jack Tocho        66.0
87          Jalen Myrick        70.0
88          Jeremy Clark        66.0
89         Jourdan Lewis        79.0
90            Kevin King        77.0
91       Marlon Humphrey        89.0
92         Marquez White        67.0
93     Marshon Lattimore        90.0
94         Nate Hairston        72.0
95         Quincy Wilson        74.0
96         Rasul Douglas        75.0
97      Shaquill Griffin        84.0
98          Sidney Jones        65.0
99       Sojourn Shelton        65.0
100           Teez Tabor        74.0
101     TreDavious White        65.0
102       Treston DeCoud        70.0
103       William Likely        65.0

In [34]:
sklearn.metrics.r2_score(list(test_df['max_madden']), preds)

0.13568402918524525

In [35]:
se = pd.Series(list(preds))

In [36]:
test_df['preds'] = se.values

In [37]:
result_df = test_df[['full_name', 'max_madden', 'preds', 'position_group_rank']]
result_df = result_df.rename(columns={'position_group_rank':'draft_position', 'preds':'predicted_madden'})
result_df.to_csv(r'C:\Users\B\Desktop\results.csv',index=False)
result_df

               full_name  max_madden  predicted_madden  draft_position
71        Adoree Jackson        83.0              77.1             5.0
72   Ahkello Witherspoon        75.0              73.1            19.0
73         Arthur Maulet        66.0              70.4            48.0
74        Ashton Lampkin        65.0              72.2            49.0
75           Brian Allen        69.0              75.8            36.0
76        Cameron Sutton        69.0              76.5            22.0
77    Channing Stribling        62.0              72.1            50.0
78        Chidobe Awuzie        82.0              78.7            17.0
79    Cordrea Tankersley        74.0              77.3            24.0
80            Corn Elder        70.0              69.8            33.0
81        Damontae Kazee        79.0              74.2            31.0
82         Ezra Robinson        62.0              69.4            52.0
83         Fabian Moreau        74.0              88.9            20.0
84         Gareon Conley        79.0              78.0             6.0
85         Howard Wilson        69.0              69.6            30.0
86            Jack Tocho        66.0              68.1            47.0
87          Jalen Myrick        70.0              77.7            45.0
88          Jeremy Clark        66.0              71.1            41.0
89         Jourdan Lewis        79.0              70.4            21.0
90            Kevin King        77.0              74.6             9.0
91       Marlon Humphrey        89.0              76.5             4.0
92         Marquez White        67.0              71.5            43.0
93     Marshon Lattimore        90.0              80.1             2.0
94         Nate Hairston        72.0              63.8            34.0
95         Quincy Wilson        74.0              68.8            13.0
96         Rasul Douglas        75.0              73.6            25.0
97      Shaquill Griffin        84.0              81.2            57.0
98          Sidney Jones        65.0              70.7            12.0
99       Sojourn Shelton        65.0              70.9            58.0
100           Teez Tabor        74.0              73.5            15.0
101     TreDavious White        65.0              78.1             8.0
102       Treston DeCoud        70.0              68.2            35.0
103       William Likely        65.0              76.1            59.0

In [21]:
result_df.sort_values(by=['predicted_madden'], ascending=False)

                 full_name  max_madden  predicted_madden  draft_position
121         Kendall Fuller        87.0              82.9            18.0
130  Vernon Hargreaves III        65.0              80.2             3.0
107   Briean Boddy-Calhoun        80.0              79.6            38.0
128         Taveze Calhoun        64.0              78.9            50.0
132    William Jackson III        84.0              78.5             6.0
114           Jalen Ramsey        97.0              77.8             1.0
112              Eli Apple        77.0              77.1             2.0
117         Jonathan Jones        83.0              76.8            44.0
123          Kevon Seymour        76.0              76.1            34.0
104          Anthony Brown        79.0              75.9            30.0
127             Sean Davis        73.0              75.7            11.0
120            Ken Crawley        82.0              74.9            46.0
115        James Bradberry        81.0              74.7            13.0
106       Brandon Williams        89.0              73.9            19.0
108             D.J. White        69.0              73.7            29.0
105            Artie Burns        81.0              73.3             7.0
111        Deandre Elliott        66.0              73.2            40.0
131           Will Redmond        68.0              73.2            14.0
113            Eric Murray        72.0              73.0            22.0
119       Keivarae Russell        71.0              72.7            16.0
126       Rashard Robinson        76.0              71.8            26.0
110        De'Vante Harris        68.0              71.6            39.0
122         Kevin Peterson        67.0              71.3            47.0
129            Tavon Young        80.0              71.0            21.0
134           Zack Sanchez        67.0              70.9            27.0
125         Maurice Canady        73.0              70.8            32.0
133          Xavien Howard        83.0              70.5             8.0
118          Juston Burris        70.0              70.2            23.0
124    Mackensie Alexander        77.0              68.1             9.0
109           Daryl Worley        75.0              68.1            17.0
116           Jimmy Pruitt        65.0              66.9            43.0

In [22]:
pd.DataFrame(result_df.sort_values(by=['max_madden'], ascending=False)['full_name'])

                 full_name
114           Jalen Ramsey
106       Brandon Williams
121         Kendall Fuller
132    William Jackson III
133          Xavien Howard
117         Jonathan Jones
120            Ken Crawley
115        James Bradberry
105            Artie Burns
107   Briean Boddy-Calhoun
129            Tavon Young
104          Anthony Brown
124    Mackensie Alexander
112              Eli Apple
126       Rashard Robinson
123          Kevon Seymour
109           Daryl Worley
127             Sean Davis
125         Maurice Canady
113            Eric Murray
119       Keivarae Russell
118          Juston Burris
108             D.J. White
131           Will Redmond
110        De'Vante Harris
122         Kevin Peterson
134           Zack Sanchez
111        Deandre Elliott
116           Jimmy Pruitt
130  Vernon Hargreaves III
128         Taveze Calhoun

In [45]:
pd.DataFrame(result_df.sort_values(by=['preds'], ascending=False)['full_name'])

              full_name
93      Ezekiel Elliott
85         Alex Collins
90        Derrick Henry
95        Jordan Howard
104          Tra Carson
92      Devontae Booker
102       Peyton Barber
103   Shadrach Thornton
94    Jonathan Williams
98        Kelvin Taylor
96        Josh Ferguson
101        Paul Perkins
107   Wendell Smallwood
99        Kenneth Dixon
89   Deandre Washington
100        Kenyan Drake
106         Tyler Ervin
88         Daniel Lasco
87         C.J. Prosise
86        Brandon Wilds
97       Keith Marshall
105          Tre Madden
91        Devon Johnson

In [46]:
pd.DataFrame(result_df.sort_values(by=['position_group_rank'], ascending=True)['full_name'])

              full_name
93      Ezekiel Elliott
90        Derrick Henry
100        Kenyan Drake
87         C.J. Prosise
106         Tyler Ervin
99        Kenneth Dixon
92      Devontae Booker
89   Deandre Washington
101        Paul Perkins
95        Jordan Howard
107   Wendell Smallwood
94    Jonathan Williams
85         Alex Collins
98        Kelvin Taylor
88         Daniel Lasco
97       Keith Marshall
86        Brandon Wilds
91        Devon Johnson
96        Josh Ferguson
102       Peyton Barber
103   Shadrach Thornton
104          Tra Carson
105          Tre Madden