In [1]:
import pandas as pd

In [2]:
input_file = "rb_rank_of_pics.csv"
output_file = input_file.replace(".csv", ".json")  #file for sankey chart

data=pd.read_csv(input_file)
data.drop(['Unnamed: 0'], axis=1, inplace=True)
data.sort_values(by=['position_group_rank'],inplace=True)
data.head(3)

,full_name,ElasticNetCV,ElasticNetCV Bins,max_madden,madden_cat,position_group_rank
0,Todd Gurley,83.694030,80,80.0,80,1.0
2,Melvin Gordon,80.130889,80,87.0,80,2.0
4,T.J. Yeldon,77.760836,70,80.0,80,3.0

In [3]:
data['position_group_rank'] = data['position_group_rank'].astype(int)
data['ElasticNetCV Bins'] = data['ElasticNetCV Bins'].astype(int)
data.head(3)

,full_name,ElasticNetCV,ElasticNetCV Bins,max_madden,madden_cat,position_group_rank
0,Todd Gurley,83.694030,80,80.0,80,1
2,Melvin Gordon,80.130889,80,87.0,80,2
4,T.J. Yeldon,77.760836,70,80.0,80,3

In [4]:
colDraft='position_group_rank'
first_col = data.pop(colDraft)
data.insert(0, colDraft, first_col)

In [5]:
data.head()

,position_group_rank,full_name,ElasticNetCV,ElasticNetCV Bins,max_madden,madden_cat
0,1,Todd Gurley,83.694030,80,80.0,80
2,2,Melvin Gordon,80.130889,80,87.0,80
4,3,T.J. Yeldon,77.760836,70,80.0,80
9,4,Ameer Abdullah,75.688667,70,82.0,80
1,5,Tevin Coleman,80.664365,80,86.0,80

In [6]:
data=data[['position_group_rank','full_name','madden_cat','ElasticNetCV Bins']]
data.head()

   position_group_rank       full_name  madden_cat  ElasticNetCV Bins
0                    1     Todd Gurley          80                 80
2                    2   Melvin Gordon          80                 80
4                    3     T.J. Yeldon          80                 70
9                    4  Ameer Abdullah          80                 70
1                    5   Tevin Coleman          80                 80

In [7]:
data = data.reset_index(drop=True)
data.head()

   position_group_rank       full_name  madden_cat  ElasticNetCV Bins
0                    1     Todd Gurley          80                 80
1                    2   Melvin Gordon          80                 80
2                    3     T.J. Yeldon          80                 70
3                    4  Ameer Abdullah          80                 70
4                    5   Tevin Coleman          80                 80

In [8]:
data['NAME']=data['position_group_rank'].astype(str)+' '+data['full_name']
data['MAX_MADDEN']=data['madden_cat'].astype(str)+' Max Madden'
data['PRED_MADDEN']=data['ElasticNetCV Bins'].astype(str)+' Predicted Madden'
data.head()

,position_group_rank,full_name,madden_cat,ElasticNetCV Bins,NAME,MAX_MADDEN,PRED_MADDEN
0,1,Todd Gurley,80,80,1 Todd Gurley,80 Max Madden,80 Predicted Madden
1,2,Melvin Gordon,80,80,2 Melvin Gordon,80 Max Madden,80 Predicted Madden
2,3,T.J. Yeldon,80,70,3 T.J. Yeldon,80 Max Madden,70 Predicted Madden
3,4,Ameer Abdullah,80,70,4 Ameer Abdullah,80 Max Madden,70 Predicted Madden
4,5,Tevin Coleman,80,80,5 Tevin Coleman,80 Max Madden,80 Predicted Madden

In [9]:
data=data[:24]  #24 seems to look best in sankey - good space distribution
data

,position_group_rank,full_name,madden_cat,ElasticNetCV Bins,NAME,MAX_MADDEN,PRED_MADDEN
0,1,Todd Gurley,80,80,1 Todd Gurley,80 Max Madden,80 Predicted Madden
1,2,Melvin Gordon,80,80,2 Melvin Gordon,80 Max Madden,80 Predicted Madden
2,3,T.J. Yeldon,80,70,3 T.J. Yeldon,80 Max Madden,70 Predicted Madden
3,4,Ameer Abdullah,80,70,4 Ameer Abdullah,80 Max Madden,70 Predicted Madden
4,5,Tevin Coleman,80,80,5 Tevin Coleman,80 Max Madden,80 Predicted Madden
5,6,Duke Johnson,80,70,6 Duke Johnson,80 Max Madden,70 Predicted Madden
6,7,Matt Jones,70,70,7 Matt Jones,70 Max Madden,70 Predicted Madden
7,8,Jeremy Langford,70,70,8 Jeremy Langford,70 Max Madden,70 Predicted Madden
8,10,Javorius Allen,70,70,10 Javorius Allen,70 Max Madden,70 Predicted Madden
9,11,Mike Davis,70,70,11 Mike Davis,70 Max Madden,70 Predicted Madden
10,12,David Cobb,70,60,12 David Cobb,70 Max Madden,60 Predicted Madden
11,13,Jay Ajayi,80,70,13 Jay Ajayi,80 Max Madden,70 Predicted Madden
12,14,Karlos Williams,60,70,14 Karlos Williams,60 Max Madden,70 Predicted Madden
13,16,Cameron Artis-Payne,70,70,16 Cameron Artis-Payne,70 Max Madden,70 Predicted Madden
14,17,Josh Robinson,60,60,17 Josh Robinson,60 Max Madden,60 Predicted Madden
15,18,Marcus Murphy,70,60,18 Marcus Murphy,70 Max Madden,60 Predicted Madden
16,20,Kenny Hilliard,60,60,20 Kenny Hilliard,60 Max Madden,60 Predicted Madden
17,25,Dominique Brown,60,60,25 Dominique Brown,60 Max Madden,60 Predicted Madden
18,26,Jahwan Edwards,60,60,26 Jahwan Edwards,60 Max Madden,60 Predicted Madden
19,27,Malcolm Brown,70,70,27 Malcolm Brown,70 Max Madden,70 Predicted Madden
20,28,Michael Dyer,60,70,28 Michael Dyer,60 Max Madden,70 Predicted Madden
21,29,Terrence Magee,60,60,29 Terrence Magee,60 Max Madden,60 Predicted Madden
22,30,Thomas Rawls,80,60,30 Thomas Rawls,80 Max Madden,60 Predicted Madden
23,31,Trey Williams,60,60,31 Trey Williams,60 Max Madden,60 Predicted Madden

In [10]:
i=0
nameNodes=[]
maxMaddenNodes=[]
predMaddenNodes=[]
nodesSorted=[]
links=[]
strJson=""
for index, row in data.iterrows():
    # parse from left to right, then down. Print each new node
    name= row['NAME']
    maxMadden= row['MAX_MADDEN']
    predMadden= row['PRED_MADDEN']
    linkName=row['full_name']
    
    if name not in nameNodes:
        nameNodes.append(name)
        nodesSorted.append(name)
        i+=1
        if maxMadden not in maxMaddenNodes:
            maxMaddenNodes.append(maxMadden) 
            nodesSorted.append(maxMadden)
            i+=1
        if predMadden not in predMaddenNodes:
            predMaddenNodes.append(predMadden)
            nodesSorted.append(predMadden)
            i+=1
        
    #get Node id
    nameIdx=nodesSorted.index(name)
    maxMaddeenIdx=nodesSorted.index(maxMadden)
    predMaddeneIdx=nodesSorted.index(predMadden)
    links.append([nameIdx,maxMaddeenIdx,predMaddeneIdx,linkName])
    #{"source":18,"target":15,"value":1},
    #strJson+="{}:{},{}:{}{}{}".format("{\"source\"", nameIdx, "\"target\"","\"", node,"\"},\n")

print(links)

[[0, 1, 2, 'Todd Gurley'], [3, 1, 2, 'Melvin Gordon'], [4, 1, 5, 'T.J. Yeldon'], [6, 1, 5, 'Ameer Abdullah'], [7, 1, 2, 'Tevin Coleman'], [8, 1, 5, 'Duke Johnson'], [9, 10, 5, 'Matt Jones'], [11, 10, 5, 'Jeremy Langford'], [12, 10, 5, 'Javorius Allen'], [13, 10, 5, 'Mike Davis'], [14, 10, 15, 'David Cobb'], [16, 1, 5, 'Jay Ajayi'], [17, 18, 5, 'Karlos Williams'], [19, 10, 5, 'Cameron Artis-Payne'], [20, 18, 15, 'Josh Robinson'], [21, 10, 15, 'Marcus Murphy'], [22, 18, 15, 'Kenny Hilliard'], [23, 18, 15, 'Dominique Brown'], [24, 18, 15, 'Jahwan Edwards'], [25, 10, 5, 'Malcolm Brown'], [26, 18, 5, 'Michael Dyer'], [27, 18, 15, 'Terrence Magee'], [28, 1, 15, 'Thomas Rawls'], [29, 18, 15, 'Trey Williams']]

In [11]:
def createLinks(links):
    strJson=""
    strJson+="{}".format("\"links\":[\n")
    i=0
    for link in links:
        #{"source":0,"target":1,"value":1},
        strJson+="{}:{},{}:{},{}:{},{}:{},{}:{}{}".format("{\"id\"", i,"\"id_next\"", i+1,"\"source\"", link[0], "\"target\"", link[1],"\"value\":1,\"label\"","\""+link[3],"\"},\n")
        i+=1
        strJson+="{}:{},{}:{},{}:{},{}:{},{}:{}{}".format("{\"id\"", i,"\"id_next\"", i-1,"\"source\"", link[1], "\"target\"", link[2],"\"value\":1,\"label\"","\""+link[3],"\"},\n")
        i+=1
    strJson=strJson[:-2]   
    strJson+="\n"
    strJson+="{}".format("]}\n")     
    return strJson

In [12]:
def createNodes(nodesSorted):
    strJson=""
    ind=0
    strJson="{}".format("{\n")
    strJson+="{}".format("\"nodes\":[\n")
    for node in nodesSorted:
        strJson+="{}:{},{}:{}{}{}".format("{\"node\"", ind, "\"name\"","\"", node,"\"},\n")
        ind+=1
    strJson=strJson[:-2]   
    strJson+="\n"
    strJson+="{}".format("],\n") 
    return strJson
#string[:-1]

In [13]:
strJsonLinks=createLinks(links)
print(strJsonLinks)

"links":[
{"id":0,"id_next":1,"source":0,"target":1,"value":1,"label":"Todd Gurley"},
{"id":1,"id_next":0,"source":1,"target":2,"value":1,"label":"Todd Gurley"},
{"id":2,"id_next":3,"source":3,"target":1,"value":1,"label":"Melvin Gordon"},
{"id":3,"id_next":2,"source":1,"target":2,"value":1,"label":"Melvin Gordon"},
{"id":4,"id_next":5,"source":4,"target":1,"value":1,"label":"T.J. Yeldon"},
{"id":5,"id_next":4,"source":1,"target":5,"value":1,"label":"T.J. Yeldon"},
{"id":6,"id_next":7,"source":6,"target":1,"value":1,"label":"Ameer Abdullah"},
{"id":7,"id_next":6,"source":1,"target":5,"value":1,"label":"Ameer Abdullah"},
{"id":8,"id_next":9,"source":7,"target":1,"value":1,"label":"Tevin Coleman"},
{"id":9,"id_next":8,"source":1,"target":2,"value":1,"label":"Tevin Coleman"},
{"id":10,"id_next":11,"source":8,"target":1,"value":1,"label":"Duke Johnson"},
{"id":11,"id_next":10,"source":1,"target":5,"value":1,"label":"Duke Johnson"},
{"id":12,"id_next":13,"source":9,"target":10,"value":1,"label":"Matt Jones"},
{"id":13,"id_next":12,"source":10,"target":5,"value":1,"label":"Matt Jones"},
{"id":14,"id_next":15,"source":11,"target":10,"value":1,"label":"Jeremy Langford"},
{"id":15,"id_next":14,"source":10,"target":5,"value":1,"label":"Jeremy Langford"},
{"id":16,"id_next":17,"source":12,"target":10,"value":1,"label":"Javorius Allen"},
{"id":17,"id_next":16,"source":10,"target":5,"value":1,"label":"Javorius Allen"},
{"id":18,"id_next":19,"source":13,"target":10,"value":1,"label":"Mike Davis"},
{"id":19,"id_next":18,"source":10,"target":5,"value":1,"label":"Mike Davis"},
{"id":20,"id_next":21,"source":14,"target":10,"value":1,"label":"David Cobb"},
{"id":21,"id_next":20,"source":10,"target":15,"value":1,"label":"David Cobb"},
{"id":22,"id_next":23,"source":16,"target":1,"value":1,"label":"Jay Ajayi"},
{"id":23,"id_next":22,"source":1,"target":5,"value":1,"label":"Jay Ajayi"},
{"id":24,"id_next":25,"source":17,"target":18,"value":1,"label":"Karlos Williams"},
{"id":25,"id_next":24,"source":18,"target":5,"value":1,"label":"Karlos Williams"},
{"id":26,"id_next":27,"source":19,"target":10,"value":1,"label":"Cameron Artis-Payne"},
{"id":27,"id_next":26,"source":10,"target":5,"value":1,"label":"Cameron Artis-Payne"},
{"id":28,"id_next":29,"source":20,"target":18,"value":1,"label":"Josh Robinson"},
{"id":29,"id_next":28,"source":18,"target":15,"value":1,"label":"Josh Robinson"},
{"id":30,"id_next":31,"source":21,"target":10,"value":1,"label":"Marcus Murphy"},
{"id":31,"id_next":30,"source":10,"target":15,"value":1,"label":"Marcus Murphy"},
{"id":32,"id_next":33,"source":22,"target":18,"value":1,"label":"Kenny Hilliard"},
{"id":33,"id_next":32,"source":18,"target":15,"value":1,"label":"Kenny Hilliard"},
{"id":34,"id_next":35,"source":23,"target":18,"value":1,"label":"Dominique Brown"},
{"id":35,"id_next":34,"source":18,"target":15,"value":1,"label":"Dominique Brown"},
{"id":36,"id_next":37,"source":24,"target":18,"value":1,"label":"Jahwan Edwards"},
{"id":37,"id_next":36,"source":18,"target":15,"value":1,"label":"Jahwan Edwards"},
{"id":38,"id_next":39,"source":25,"target":10,"value":1,"label":"Malcolm Brown"},
{"id":39,"id_next":38,"source":10,"target":5,"value":1,"label":"Malcolm Brown"},
{"id":40,"id_next":41,"source":26,"target":18,"value":1,"label":"Michael Dyer"},
{"id":41,"id_next":40,"source":18,"target":5,"value":1,"label":"Michael Dyer"},
{"id":42,"id_next":43,"source":27,"target":18,"value":1,"label":"Terrence Magee"},
{"id":43,"id_next":42,"source":18,"target":15,"value":1,"label":"Terrence Magee"},
{"id":44,"id_next":45,"source":28,"target":1,"value":1,"label":"Thomas Rawls"},
{"id":45,"id_next":44,"source":1,"target":15,"value":1,"label":"Thomas Rawls"},
{"id":46,"id_next":47,"source":29,"target":18,"value":1,"label":"Trey Williams"},
{"id":47,"id_next":46,"source":18,"target":15,"value":1,"label":"Trey Williams"}
]}

In [14]:
strJsonNodes=createNodes(nodesSorted)
print(strJsonNodes)

{
"nodes":[
{"node":0,"name":"1 Todd Gurley"},
{"node":1,"name":"80 Max Madden"},
{"node":2,"name":"80 Predicted Madden"},
{"node":3,"name":"2 Melvin Gordon"},
{"node":4,"name":"3 T.J. Yeldon"},
{"node":5,"name":"70 Predicted Madden"},
{"node":6,"name":"4 Ameer Abdullah"},
{"node":7,"name":"5 Tevin Coleman"},
{"node":8,"name":"6 Duke Johnson"},
{"node":9,"name":"7 Matt Jones"},
{"node":10,"name":"70 Max Madden"},
{"node":11,"name":"8 Jeremy Langford"},
{"node":12,"name":"10 Javorius Allen"},
{"node":13,"name":"11 Mike Davis"},
{"node":14,"name":"12 David Cobb"},
{"node":15,"name":"60 Predicted Madden"},
{"node":16,"name":"13 Jay Ajayi"},
{"node":17,"name":"14 Karlos Williams"},
{"node":18,"name":"60 Max Madden"},
{"node":19,"name":"16 Cameron Artis-Payne"},
{"node":20,"name":"17 Josh Robinson"},
{"node":21,"name":"18 Marcus Murphy"},
{"node":22,"name":"20 Kenny Hilliard"},
{"node":23,"name":"25 Dominique Brown"},
{"node":24,"name":"26 Jahwan Edwards"},
{"node":25,"name":"27 Malcolm Brown"},
{"node":26,"name":"28 Michael Dyer"},
{"node":27,"name":"29 Terrence Magee"},
{"node":28,"name":"30 Thomas Rawls"},
{"node":29,"name":"31 Trey Williams"}
],

In [15]:
strJsonForModel=strJsonNodes+strJsonLinks
print(strJsonForModel)

{
"nodes":[
{"node":0,"name":"1 Todd Gurley"},
{"node":1,"name":"80 Max Madden"},
{"node":2,"name":"80 Predicted Madden"},
{"node":3,"name":"2 Melvin Gordon"},
{"node":4,"name":"3 T.J. Yeldon"},
{"node":5,"name":"70 Predicted Madden"},
{"node":6,"name":"4 Ameer Abdullah"},
{"node":7,"name":"5 Tevin Coleman"},
{"node":8,"name":"6 Duke Johnson"},
{"node":9,"name":"7 Matt Jones"},
{"node":10,"name":"70 Max Madden"},
{"node":11,"name":"8 Jeremy Langford"},
{"node":12,"name":"10 Javorius Allen"},
{"node":13,"name":"11 Mike Davis"},
{"node":14,"name":"12 David Cobb"},
{"node":15,"name":"60 Predicted Madden"},
{"node":16,"name":"13 Jay Ajayi"},
{"node":17,"name":"14 Karlos Williams"},
{"node":18,"name":"60 Max Madden"},
{"node":19,"name":"16 Cameron Artis-Payne"},
{"node":20,"name":"17 Josh Robinson"},
{"node":21,"name":"18 Marcus Murphy"},
{"node":22,"name":"20 Kenny Hilliard"},
{"node":23,"name":"25 Dominique Brown"},
{"node":24,"name":"26 Jahwan Edwards"},
{"node":25,"name":"27 Malcolm Brown"},
{"node":26,"name":"28 Michael Dyer"},
{"node":27,"name":"29 Terrence Magee"},
{"node":28,"name":"30 Thomas Rawls"},
{"node":29,"name":"31 Trey Williams"}
],
"links":[
{"id":0,"id_next":1,"source":0,"target":1,"value":1,"label":"Todd Gurley"},
{"id":1,"id_next":0,"source":1,"target":2,"value":1,"label":"Todd Gurley"},
{"id":2,"id_next":3,"source":3,"target":1,"value":1,"label":"Melvin Gordon"},
{"id":3,"id_next":2,"source":1,"target":2,"value":1,"label":"Melvin Gordon"},
{"id":4,"id_next":5,"source":4,"target":1,"value":1,"label":"T.J. Yeldon"},
{"id":5,"id_next":4,"source":1,"target":5,"value":1,"label":"T.J. Yeldon"},
{"id":6,"id_next":7,"source":6,"target":1,"value":1,"label":"Ameer Abdullah"},
{"id":7,"id_next":6,"source":1,"target":5,"value":1,"label":"Ameer Abdullah"},
{"id":8,"id_next":9,"source":7,"target":1,"value":1,"label":"Tevin Coleman"},
{"id":9,"id_next":8,"source":1,"target":2,"value":1,"label":"Tevin Coleman"},
{"id":10,"id_next":11,"source":8,"target":1,"value":1,"label":"Duke Johnson"},
{"id":11,"id_next":10,"source":1,"target":5,"value":1,"label":"Duke Johnson"},
{"id":12,"id_next":13,"source":9,"target":10,"value":1,"label":"Matt Jones"},
{"id":13,"id_next":12,"source":10,"target":5,"value":1,"label":"Matt Jones"},
{"id":14,"id_next":15,"source":11,"target":10,"value":1,"label":"Jeremy Langford"},
{"id":15,"id_next":14,"source":10,"target":5,"value":1,"label":"Jeremy Langford"},
{"id":16,"id_next":17,"source":12,"target":10,"value":1,"label":"Javorius Allen"},
{"id":17,"id_next":16,"source":10,"target":5,"value":1,"label":"Javorius Allen"},
{"id":18,"id_next":19,"source":13,"target":10,"value":1,"label":"Mike Davis"},
{"id":19,"id_next":18,"source":10,"target":5,"value":1,"label":"Mike Davis"},
{"id":20,"id_next":21,"source":14,"target":10,"value":1,"label":"David Cobb"},
{"id":21,"id_next":20,"source":10,"target":15,"value":1,"label":"David Cobb"},
{"id":22,"id_next":23,"source":16,"target":1,"value":1,"label":"Jay Ajayi"},
{"id":23,"id_next":22,"source":1,"target":5,"value":1,"label":"Jay Ajayi"},
{"id":24,"id_next":25,"source":17,"target":18,"value":1,"label":"Karlos Williams"},
{"id":25,"id_next":24,"source":18,"target":5,"value":1,"label":"Karlos Williams"},
{"id":26,"id_next":27,"source":19,"target":10,"value":1,"label":"Cameron Artis-Payne"},
{"id":27,"id_next":26,"source":10,"target":5,"value":1,"label":"Cameron Artis-Payne"},
{"id":28,"id_next":29,"source":20,"target":18,"value":1,"label":"Josh Robinson"},
{"id":29,"id_next":28,"source":18,"target":15,"value":1,"label":"Josh Robinson"},
{"id":30,"id_next":31,"source":21,"target":10,"value":1,"label":"Marcus Murphy"},
{"id":31,"id_next":30,"source":10,"target":15,"value":1,"label":"Marcus Murphy"},
{"id":32,"id_next":33,"source":22,"target":18,"value":1,"label":"Kenny Hilliard"},
{"id":33,"id_next":32,"source":18,"target":15,"value":1,"label":"Kenny Hilliard"},
{"id":34,"id_next":35,"source":23,"target":18,"value":1,"label":"Dominique Brown"},
{"id":35,"id_next":34,"source":18,"target":15,"value":1,"label":"Dominique Brown"},
{"id":36,"id_next":37,"source":24,"target":18,"value":1,"label":"Jahwan Edwards"},
{"id":37,"id_next":36,"source":18,"target":15,"value":1,"label":"Jahwan Edwards"},
{"id":38,"id_next":39,"source":25,"target":10,"value":1,"label":"Malcolm Brown"},
{"id":39,"id_next":38,"source":10,"target":5,"value":1,"label":"Malcolm Brown"},
{"id":40,"id_next":41,"source":26,"target":18,"value":1,"label":"Michael Dyer"},
{"id":41,"id_next":40,"source":18,"target":5,"value":1,"label":"Michael Dyer"},
{"id":42,"id_next":43,"source":27,"target":18,"value":1,"label":"Terrence Magee"},
{"id":43,"id_next":42,"source":18,"target":15,"value":1,"label":"Terrence Magee"},
{"id":44,"id_next":45,"source":28,"target":1,"value":1,"label":"Thomas Rawls"},
{"id":45,"id_next":44,"source":1,"target":15,"value":1,"label":"Thomas Rawls"},
{"id":46,"id_next":47,"source":29,"target":18,"value":1,"label":"Trey Williams"},
{"id":47,"id_next":46,"source":18,"target":15,"value":1,"label":"Trey Williams"}
]}

In [16]:
out_file = open(output_file, "w")
n = out_file.write(strJsonForModel)
out_file.close()