In [8]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import numpy as np
import sklearn.metrics

In [31]:
df = pd.read_csv("..//data_mart//reporting_b.csv")
hold_out_year = 2016

In [32]:
test_df = df.loc[df['draft_year'] == hold_out_year]

In [33]:
bool_series = pd.notnull(df['max_madden'])
train_df = df[bool_series]
train_df = train_df.loc[train_df['draft_year'] != hold_out_year]

In [34]:
numerical_columns = ['college_weight_pounds_zscore', 'hw_ratio_zscore', 
                     'forty_zscore', 'vertical_zscore', 'bench_zscore', 'broad_zscore', 'threecone_zscore', 'shuttle_zscore'
                     ,'football_spending_zscore', 'rushing_rush_td_pg_cf_scaled_zscore', 
                     'rushing_rush_yds_pg_cf_scaled_zscore','rushing_scrim_plays_pg_cf_scaled_zscore'
                     ,'rushing_scrim_tds_pg_cf_scaled_zscore', 'rushing_scrim_yds_pg_cf_scaled_zscore']

In [35]:
X = train_df[numerical_columns]
y = train_df['max_madden']

In [36]:
regr = RandomForestRegressor(random_state=0)
X = X.fillna(0)
regr.fit(X,y)

c:\users\b\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [37]:
test_df = test_df.fillna(0)
preds = regr.predict(test_df[numerical_columns])

In [38]:
test_df['max_madden'] = test_df['max_madden'].replace(0, 65)
print(test_df[['full_name', 'max_madden']])

              full_name  max_madden
85         Alex Collins        81.0
86        Brandon Wilds        65.0
87         C.J. Prosise        74.0
88         Daniel Lasco        68.0
89   Deandre Washington        74.0
90        Derrick Henry        86.0
91        Devon Johnson        62.0
92      Devontae Booker        76.0
93      Ezekiel Elliott        94.0
94    Jonathan Williams        67.0
95        Jordan Howard        85.0
96        Josh Ferguson        65.0
97       Keith Marshall        71.0
98        Kelvin Taylor        67.0
99        Kenneth Dixon        76.0
100        Kenyan Drake        82.0
101        Paul Perkins        77.0
102       Peyton Barber        77.0
103   Shadrach Thornton        65.0
104          Tra Carson        62.0
105          Tre Madden        70.0
106         Tyler Ervin        67.0
107   Wendell Smallwood        72.0

In [39]:
sklearn.metrics.r2_score(list(test_df['max_madden']), preds)

0.16819931856899462

In [40]:
se = pd.Series(list(preds))

In [41]:
test_df['preds'] = se.values

In [59]:
result_df = test_df[['full_name', 'max_madden', 'preds', 'position_group_rank']]
result_df = result_df.rename(columns={'position_group_rank':'draft_position', 'preds':'predicted_madden'})
result_df.to_csv(r'C:\Users\B\Desktop\results.csv',index=False)
result_df

              full_name  max_madden  predicted_madden  draft_position
85         Alex Collins        81.0              82.1            13.0
86        Brandon Wilds        65.0              69.7            19.0
87         C.J. Prosise        74.0              70.5             4.0
88         Daniel Lasco        68.0              70.9            17.0
89   Deandre Washington        74.0              73.3             8.0
90        Derrick Henry        86.0              82.1             2.0
91        Devon Johnson        62.0              66.9            20.0
92      Devontae Booker        76.0              80.3             7.0
93      Ezekiel Elliott        94.0              82.3             1.0
94    Jonathan Williams        67.0              77.5            12.0
95        Jordan Howard        85.0              80.6            10.0
96        Josh Ferguson        65.0              77.1            22.0
97       Keith Marshall        71.0              68.0            18.0
98        Kelvin Taylor        67.0              77.4            16.0
99        Kenneth Dixon        76.0              74.1             6.0
100        Kenyan Drake        82.0              72.4             3.0
101        Paul Perkins        77.0              75.9             9.0
102       Peyton Barber        77.0              78.9            23.0
103   Shadrach Thornton        65.0              77.5            25.0
104          Tra Carson        62.0              80.4            27.0
105          Tre Madden        70.0              67.1            28.0
106         Tyler Ervin        67.0              72.3             5.0
107   Wendell Smallwood        72.0              75.1            11.0

In [58]:
result_df.sort_values(by=['predicted_madden'], ascending=False)

              full_name  max_madden  predicted_madden  draft_position
93      Ezekiel Elliott        94.0              82.3             1.0
85         Alex Collins        81.0              82.1            13.0
90        Derrick Henry        86.0              82.1             2.0
95        Jordan Howard        85.0              80.6            10.0
104          Tra Carson        62.0              80.4            27.0
92      Devontae Booker        76.0              80.3             7.0
102       Peyton Barber        77.0              78.9            23.0
103   Shadrach Thornton        65.0              77.5            25.0
94    Jonathan Williams        67.0              77.5            12.0
98        Kelvin Taylor        67.0              77.4            16.0
96        Josh Ferguson        65.0              77.1            22.0
101        Paul Perkins        77.0              75.9             9.0
107   Wendell Smallwood        72.0              75.1            11.0
99        Kenneth Dixon        76.0              74.1             6.0
89   Deandre Washington        74.0              73.3             8.0
100        Kenyan Drake        82.0              72.4             3.0
106         Tyler Ervin        67.0              72.3             5.0
88         Daniel Lasco        68.0              70.9            17.0
87         C.J. Prosise        74.0              70.5             4.0
86        Brandon Wilds        65.0              69.7            19.0
97       Keith Marshall        71.0              68.0            18.0
105          Tre Madden        70.0              67.1            28.0
91        Devon Johnson        62.0              66.9            20.0

In [44]:
pd.DataFrame(result_df.sort_values(by=['max_madden'], ascending=False)['full_name'])

              full_name
93      Ezekiel Elliott
90        Derrick Henry
95        Jordan Howard
100        Kenyan Drake
85         Alex Collins
102       Peyton Barber
101        Paul Perkins
99        Kenneth Dixon
92      Devontae Booker
87         C.J. Prosise
89   Deandre Washington
107   Wendell Smallwood
97       Keith Marshall
105          Tre Madden
88         Daniel Lasco
98        Kelvin Taylor
94    Jonathan Williams
106         Tyler Ervin
86        Brandon Wilds
103   Shadrach Thornton
96        Josh Ferguson
91        Devon Johnson
104          Tra Carson

In [45]:
pd.DataFrame(result_df.sort_values(by=['preds'], ascending=False)['full_name'])

              full_name
93      Ezekiel Elliott
85         Alex Collins
90        Derrick Henry
95        Jordan Howard
104          Tra Carson
92      Devontae Booker
102       Peyton Barber
103   Shadrach Thornton
94    Jonathan Williams
98        Kelvin Taylor
96        Josh Ferguson
101        Paul Perkins
107   Wendell Smallwood
99        Kenneth Dixon
89   Deandre Washington
100        Kenyan Drake
106         Tyler Ervin
88         Daniel Lasco
87         C.J. Prosise
86        Brandon Wilds
97       Keith Marshall
105          Tre Madden
91        Devon Johnson

In [46]:
pd.DataFrame(result_df.sort_values(by=['position_group_rank'], ascending=True)['full_name'])

              full_name
93      Ezekiel Elliott
90        Derrick Henry
100        Kenyan Drake
87         C.J. Prosise
106         Tyler Ervin
99        Kenneth Dixon
92      Devontae Booker
89   Deandre Washington
101        Paul Perkins
95        Jordan Howard
107   Wendell Smallwood
94    Jonathan Williams
85         Alex Collins
98        Kelvin Taylor
88         Daniel Lasco
97       Keith Marshall
86        Brandon Wilds
91        Devon Johnson
96        Josh Ferguson
102       Peyton Barber
103   Shadrach Thornton
104          Tra Carson
105          Tre Madden