This notebook exists to help perform some transformations and inspections of data.  Goal is to eventually collapse this into a .py file.

Data Sources / credits:
* City and State Zip search: https://pypi.org/project/uszipcode/
* Zip codes from: http://federalgovernmentzipcodes.us/free-zipcode-database-Primary.csv
* Weather station zips: https://www1.ncdc.noaa.gov/pub/data/normals/1981-2010/station-inventories/zipcodes-normals-stations.txt

In [33]:
# Install some helpful libraries
#!pip install uszipcode
#!pip install pygeocoder
#!pip install requests
#!pip install geopy

# Importing necessary libraries
import pandas as pd
from uszipcode import SearchEngine
search = SearchEngine(simple_zipcode=True)
from math import radians, sin, cos, sqrt, asin
from geopy.geocoders import Nominatim
from functools import partial

# Setup definition we'll need to calculate GPS coordinate distance
def haversine(lat1, lon1, lat2, lon2):
    R = 6372.8  # Earth radius in kilometers
    dLat = radians(lat2 - lat1)
    dLon = radians(lon2 - lon1)
    lat1 = radians(lat1)
    lat2 = radians(lat2)
    a = sin(dLat / 2)**2 + cos(lat1) * cos(lat2) * sin(dLon / 2)**2
    c = 2 * asin(sqrt(a))
    return R * c

# Setup our geolocator
geolocator = Nominatim(user_agent="college-town-weather-extractor")
geocode = partial(geolocator.geocode, language="en")

In [2]:
# Reading the files
fpath = './noaa/mly-tmax-normal.txt'
max_df = pd.read_csv(fpath, delim_whitespace=True, header=None)
fpath = './noaa/mly-tmin-normal.txt'
min_df = pd.read_csv(fpath, delim_whitespace=True, header=None)
fpath = './college-city-mapping.csv'
city_df = pd.read_csv(fpath,header=0)
city_df['min_jan'],city_df['min_feb'],city_df['min_mar'],city_df['min_apr'],city_df['min_may'],city_df['min_jun'],city_df['min_jul'],city_df['min_aug'],city_df['min_sep'],city_df['min_oct'],city_df['min_nov'],city_df['min_dec']='','','','','','','','','','','',''
city_df['max_jan'],city_df['max_feb'],city_df['max_mar'],city_df['max_apr'],city_df['max_may'],city_df['max_jun'],city_df['max_jul'],city_df['max_aug'],city_df['max_sep'],city_df['max_oct'],city_df['max_nov'],city_df['max_dec']='','','','','','','','','','','',''
fpath = './free-zipcode-database-primary.csv'
zip_df = pd.read_csv(fpath,header=0)
fpath = './zipcodes-normals-stations.txt'
zstation_df = pd.read_fwf(fpath,header=None,converters={1: lambda x: int(x)})
zstation_df.rename(columns={0:'station_id',1:'zip',2:'city'}, inplace=True)
fpath = './allstations.txt'
gstation_df = pd.read_fwf(fpath,header=None,converters={1: lambda x: float(x)})
gstation_df.rename(columns={0:'station_id',1:'lat',2:'long',4:'state'}, inplace=True)

In [3]:
# strip indicator tag about quality of data, convert to fahrenheit
for h in range(0,max_df.shape[0]):
    for w in range(0,max_df.shape[1]):
        if (len(max_df[w][h])) == 11:
            continue
        else:
            l = len(max_df[w][h])
            max_df[w][h] = float(max_df[w][h][0:l-1])/10

for h in range(0,min_df.shape[0]):
    for w in range(0,min_df.shape[1]):
        if (len(min_df[w][h])) == 11:
            continue
        else:
            l = len(min_df[w][h])
            min_df[w][h] = float(min_df[w][h][0:l-1])/10

max_df.rename(columns={0:'station_id',1:'january',2:'february',3:'march',4:'april',5:'may',6:'june',7:'july',8:'august',9:'september',10:'october',11:'november',12:'december'}, inplace=True)
min_df.rename(columns={0:'station_id',1:'january',2:'february',3:'march',4:'april',5:'may',6:'june',7:'july',8:'august',9:'september',10:'october',11:'november',12:'december'}, inplace=True)

In [4]:
# v1: you probably don't want to run this one. It looks for exact zip matches
# by iterating through each city-zip pairing to extract weather station
for i in range(city_df.shape[0]):
    sid =[]
    city,state = city_df['Geographic Location'][i].split(",")
    result = search.by_city_and_state(city,state)
    for z in result:
        ctr = 0
        for zm in zstation_df.zip:
            if int(z.zipcode) == int(zm):
                # yes, we're picking the first one we find; weather should be similar
                sid.append(zstation_df['station_id'][ctr])
                break
            ctr+=1
    if len(sid) == 0:
        # nothing found in that zip
        continue
    else:
        sname = str(sid[0])
        ctr=0
        for sn in max_df.station_id:
            if sname == sn:
                city_df.at[i,'max_jan'] = max_df.loc[ctr][1]
                city_df.at[i,'max_feb'] = max_df.loc[ctr][2]
                city_df.at[i,'max_mar'] = max_df.loc[ctr][3]
                city_df.at[i,'max_apr'] = max_df.loc[ctr][4]
                city_df.at[i,'max_may'] = max_df.loc[ctr][5]
                city_df.at[i,'max_jun'] = max_df.loc[ctr][6]
                city_df.at[i,'max_jul'] = max_df.loc[ctr][7]
                city_df.at[i,'max_aug'] = max_df.loc[ctr][8]
                city_df.at[i,'max_sep'] = max_df.loc[ctr][9]
                city_df.at[i,'max_oct'] = max_df.loc[ctr][10]
                city_df.at[i,'max_nov'] = max_df.loc[ctr][11]
                city_df.at[i,'max_dec'] = max_df.loc[ctr][12]
            ctr+=1
        ctr=0
        for sn in min_df.station_id:
            if sname == sn:
                city_df.at[i,'min_jan'] = min_df.loc[ctr][1]
                city_df.at[i,'min_feb'] = min_df.loc[ctr][2]
                city_df.at[i,'min_mar'] = min_df.loc[ctr][3]
                city_df.at[i,'min_apr'] = min_df.loc[ctr][4]
                city_df.at[i,'min_may'] = min_df.loc[ctr][5]
                city_df.at[i,'min_jun'] = min_df.loc[ctr][6]
                city_df.at[i,'min_jul'] = min_df.loc[ctr][7]
                city_df.at[i,'min_aug'] = min_df.loc[ctr][8]
                city_df.at[i,'min_sep'] = min_df.loc[ctr][9]
                city_df.at[i,'min_oct'] = min_df.loc[ctr][10]
                city_df.at[i,'min_nov'] = min_df.loc[ctr][11]
                city_df.at[i,'min_dec'] = min_df.loc[ctr][12]
            ctr+=1

In [77]:
# v2, doing it better
for i in range(city_df.shape[0]):
    city,state = city_df['Geographic Location'][i].split(",")
    location = geolocator.geocode(city_df['Geographic Location'][i])
    clat,clon = location.latitude, location.longitude
    #print("Searching for station closest to:",clat,clon)
    ctr = 0
    lowest_val = []
    lowest_pos = []
    for la,lo in zip(gstation_df['lat'],gstation_df['long']):
        distance = haversine(clat,clon,la,lo)
        if ctr == 0:
            lowest_val.append(distance)
            lowest_pos.append(ctr)
        else:
            if lowest_val[0] > distance:
                lowest_val[0] = distance
                lowest_pos[0] = ctr
        ctr+=1
    #print("lowest haversine value =",lowest_val,"for station",list(gstation_df.loc[lowest_pos[0]])[0])
    #print("with lat:",list(gstation_df.loc[lowest_pos[0]])[1],"long:",list(gstation_df.loc[lowest_pos[0]])[2])
    sname = list(gstation_df.loc[lowest_pos[0]])[0]
    ctr=0
    for sn in max_df.station_id:
        if sname == sn:
            city_df.at[i,'max_jan'] = max_df.loc[ctr][1]
            city_df.at[i,'max_feb'] = max_df.loc[ctr][2]
            city_df.at[i,'max_mar'] = max_df.loc[ctr][3]
            city_df.at[i,'max_apr'] = max_df.loc[ctr][4]
            city_df.at[i,'max_may'] = max_df.loc[ctr][5]
            city_df.at[i,'max_jun'] = max_df.loc[ctr][6]
            city_df.at[i,'max_jul'] = max_df.loc[ctr][7]
            city_df.at[i,'max_aug'] = max_df.loc[ctr][8]
            city_df.at[i,'max_sep'] = max_df.loc[ctr][9]
            city_df.at[i,'max_oct'] = max_df.loc[ctr][10]
            city_df.at[i,'max_nov'] = max_df.loc[ctr][11]
            city_df.at[i,'max_dec'] = max_df.loc[ctr][12]
        ctr+=1
    ctr=0
    for sn in min_df.station_id:
        if sname == sn:
            city_df.at[i,'min_jan'] = min_df.loc[ctr][1]
            city_df.at[i,'min_feb'] = min_df.loc[ctr][2]
            city_df.at[i,'min_mar'] = min_df.loc[ctr][3]
            city_df.at[i,'min_apr'] = min_df.loc[ctr][4]
            city_df.at[i,'min_may'] = min_df.loc[ctr][5]
            city_df.at[i,'min_jun'] = min_df.loc[ctr][6]
            city_df.at[i,'min_jul'] = min_df.loc[ctr][7]
            city_df.at[i,'min_aug'] = min_df.loc[ctr][8]
            city_df.at[i,'min_sep'] = min_df.loc[ctr][9]
            city_df.at[i,'min_oct'] = min_df.loc[ctr][10]
            city_df.at[i,'min_nov'] = min_df.loc[ctr][11]
            city_df.at[i,'min_dec'] = min_df.loc[ctr][12]
        ctr+=1

In [78]:
# to do: research missing values
city_df

,College,Geographic Location,min_jan,min_feb,min_mar,min_apr,min_may,min_jun,min_jul,min_aug,...,max_mar,max_apr,max_may,max_jun,max_jul,max_aug,max_sep,max_oct,max_nov,max_dec
0,Abilene Christian,"Abilene, TX",33,36.7,44.1,51.9,61.4,68.5,72,71.6,...,68.6,77.3,84.6,90.5,94.2,94,86.8,77.3,66.3,56.9
1,Air Force,"Colorado Springs, CO",17.7,19.5,26,33.3,42.7,51.3,56.9,55.7,...,52.1,59.8,69.1,79,84.8,81.6,74.5,63,51,42.1
2,Akron,"Akron, OH",22.2,23.8,30.9,41.7,51.3,60.9,64.8,63.5,...,47.8,60.4,70.2,79.4,83,81.6,73.5,61.4,50,37.9
3,Alabama,"Tuscaloosa, AL",34.9,38.4,45.1,51.6,61,68.5,72.1,71.6,...,69.7,77.2,84.1,90.2,92.7,92.6,87.7,77.7,67.7,58.2
4,Alabama State,"Montgomery, AL",,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Western Michigan,"Kalamazoo, MI",18,19.8,27.5,38.2,47.9,57.3,62.1,60.3,...,45.5,59.7,70,79.2,83.1,80.9,72.9,60.5,47.6,34.8
240,Wisconsin,"Madison, WI",9.6,13.2,23.9,35.4,45.9,55.5,60.1,58.3,...,44.1,58.2,69.3,78.9,82.7,81.2,73.6,61.1,46.2,31.7
241,Wyoming,"Laramie, WY",9.4,11.3,18.7,24,33.6,42.2,47.4,44.7,...,44.7,51.7,62.1,72.6,81,79.3,70.7,57.5,42.5,33.6
242,Yale,"New Haven, CT",22.2,24.9,31.2,40.2,49.3,59.7,65.5,64.9,...,47.6,58.2,68.5,77.3,82.5,80.9,74.4,63.4,53.5,42.9
243,Youngstown State,"Youngstown, OH",20.1,21.9,28.5,38.5,47.5,57,61.3,60.1,...,50.3,63.8,73.7,81.7,85.4,83.9,76.8,65.7,52.3,39.9